#!/bin/zsh

git_commit_automatically() {
  local action message
  commit_message=$( git status \
    | sed '1,/Changes to be committed/ d' \
    | sed '1,/^$/ d' \
    | sed '/^$/,$ d' \
    | while read line; do
        action=$(echo $line | awk '{print $1}' | sed "s/://")
        case $action in
          "new" ) added_changes="[add] $(echo $line | awk '{print $3}')" ;;
          "deleted" ) added_changes="[remove] $(echo $line | awk '{print $2}')" ;;
          "renamed" ) added_changes="[rename] $(echo $line | awk '{print $2 $3 $4}')" ;;
          "modified" ) added_changes="[improve] $(echo $line | awk '{print $2}')" ;;
        esac
      done
  )
  message="$message $added_changes"
  [ $# = 0 ] || str=" | $*"
  git commit -m "${message}${str}"
}

git_commit_automatically $*
