#!/bin/sh

dotfiles=( ".vimrc" ".zshrc" ".tmux.conf" "setup/Brewfile" )

function dot_help() {
  echo "usage: dot [COMMANDS] [OPTIONS]"
  echo
  echo "OPTIONS:"
  echo "  --help    Display this help messages"
  echo
  echo "COMMANDS:"
  echo "  update    Update dotfiles (git pull)"
  echo "  deploy    Be able to use dotfiles"
  echo "  clean     Remove dotfiles"
  echo "  init      Install packeges (this command excuted when you install dotfiles)"
}

function dot() {
  if [[ $# = 1 ]] ; then
    case $1 in

      "--help" ) dot_help ;;

      "update" ) 
        cd ~/dotfiles >/dev/null 2>&1
        msg=$(git pull)
        er=$?
        cd - >/dev/null 2>&1
        if [[ $msg =~ "Already up-to-date." ]] ; then
          echo "dot: dotfiles are already up-to-date."
        elif [[ $er = 0 ]] ; then
          echo "dot: dotfiles were updated."
        fi
      ;;

      "deploy" )
        for file in $(ls ~/dotfiles/commands); do
          chmod a+x ~/dotfiles/commands/$file
          ln -s ~/dotfiles/commands/$file /usr/local/bin/$file
          if [[ $? = 0 ]] ; then
            echo "deploy succeed : $file" 
          else
            echo "error! : $file"
          fi  
        done
      ;;

      "clean" )
        echo "dot: remove dotfiles? [n/y]:\c "
        read answer
        if [[ "$answer" = "y" ]] ; then
          for file in ${dotfiles[@]}; do
            rm ~/$file
          done
          rm -rf ~/dotfiles
          echo "dot: dotfiles were removed."
        fi 
      ;;

      "init" )
        if ! type brew >/dev/null 2>&1 ; then
          if [ $(uname -s) = "Darwin" ]; then
            cp ~/dotfiles/setup/Brewfile ~
            echo "dot: installing Homebrew ..."
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            brew tap Homebrew/bundle
            brew bundle
            rm ~/Brewfile
          elif [ $(uname -s) = "Linux" ]; then
            sudo apt-get install curl git ruby zsh
          else
            echo "dot: not support your OS"
          fi
        fi
        if [ ! $SHELL == "/bin/zsh" ] ; then
          echo "dot: change shell to zsh, please put your password"
          chsh -s /bin/zsh
        fi
      ;;

      * ) 
        if [[ "$1" =~ ^- ]]; then
          echo "dot: illegal option $1"
          echo
        else
          echo "dot: illegal command $1"
          echo
        fi
        dot_help && exit 1
      ;;

    esac
  else
    dot_help && exit 1
  fi
}

dot $@
