#!/bin/sh

dotfiles=( ".vimrc" ".zshrc" ".tmux.conf" "setup/Brewfile" )

function dotmanager_help() {
  echo "usage: dotmanager [COMMANDS] [OPTIONS]"
  echo
  echo "OPTIONS:"
  echo "  --help    Display this help messages"
  echo
  echo "COMMANDS:"
  echo "  update    Update dotfiles (git pull)"
  echo "  deploy    Activate commands in dotfiles/commands"
  echo "  clean     Remove dotfiles"
  echo "  init      Install packeges (this command excuted when you install dotfiles)"
}

function dotmanager() {
  if [[ $# = 1 ]] ; then
    case $1 in

      "--help" ) dotmanager_help ;;

      "update" ) 
        cd ~/dotfiles >/dev/null 2>&1
        msg=$(git pull)
        er=$?
        cd - >/dev/null 2>&1
        if [[ $msg =~ "Already up-to-date." ]] ; then
          echo "dotmanager: dotfiles are already up-to-date."
        elif [[ $er = 0 ]] ; then
          echo "dotmanager: dotfiles were updated."
        fi
      ;;

      "deploy" )
        cd /usr/local/bin
        for file in $(ls ~/dotfiles/commands); do
          pwd_=$PWD
          if [[ ! -e $file ]] ; then
           chmod a+x ~/dotfiles/commands/$file
            ln -s ~/dotfiles/commands/$file /usr/local/bin/$file
            if [[ $? = 0 ]] ; then
              echo "deploy succeed : $file" 
            else
              echo "error! : $file"
            fi  
          fi
        done
      ;;

      "clean" )
        echo "dotmanager: remove dotfiles? [n/y]: "
        read answer
        if [[ "$answer" = "y" ]] ; then
          for file in ${dotfiles[@]}; do
            unlink ~/$file
          done
          for file in $(ls ~/dotfiles/commands); do
            unlink /usr/local/bin/$file
          done
          rm -rf ~/dotfiles
          echo    "dotmanager: dotfiles were removed."
          echo    "     To install again, excute \"curl -L raw.github.com/arks22/dotfiles/master/setup/install.sh | sh\"."
          echo -e "     More information about dotfiles : \e[4mhttps://github.com/arks22/dotfiles\e[m"
        fi 
      ;;

      "init" )
        if ! type brew >/dev/null 2>&1 ; then
          if [ $(uname -s) = "Darwin" ]; then
            cp ~/dotfiles/setup/Brewfile ~
            echo "dotmanager: installing Homebrew ..."
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            brew tap Homebrew/bundle
            brew bundle
            rm ~/Brewfile
          elif [ $(uname -s) = "Linux" ]; then
            sudo apt-get install curl git ruby zsh
          else
            echo "dotmanager: not support your OS"
          fi
        fi
        if [ ! $SHELL == "/bin/zsh" ] ; then
          echo "dotmanager: change shell to zsh, please put your password"
          chsh -s /bin/zsh
        fi
      ;;

      * ) 
        if [[ "$1" =~ ^- ]]; then
          echo "dotmanager: illegal option $1"
          echo
        else
          echo "dotmanager: illegal command $1"
          echo
        fi
        dotmanager_help && exit 1
      ;;

    esac
  else
    dotmanager_help && exit 1
  fi
}

dotmanager $@
