#!/bin/sh

git_commit_automatically() {
  local commmit_message added_changes action line
  git status \
    | sed -e '1,/Changes to be committed/ d' \
    | sed '1,/^$/ d' \
    | sed '/^$/,$ d' \
    | while read line; do
    action=$(echo $line | awk '{print $1}' | sed s/://)
    case $action in
      "new" ) added_changes="[add] $(echo $line | awk '{print $3}')" ;;
      "deleted" ) added_changes="[remove] $(echo $line | awk '{print $2}')" ;;
      "renamed" ) added_changes="[rename] $(echo $line | awk '{print $2 $3 $4}')" ;;
      "modified" ) added_changes="[update] $(echo $line | awk '{print $2}')" ;;
    esac
    commmit_message="$commmit_message $added_changes"
  done
  git commit -m "$commmit_message $1"
}
