#!/bin/sh

loop() {
  while read line; do
    action=$(echo $line | awk '{print $1}' | sed "s/://")
    case $action in
      "new" ) added_changes="[add] $(echo $line | awk '{print $3}')" ;;
      "deleted" ) added_changes="[remove] $(echo $line | awk '{print $2}')" ;;
      "renamed" ) added_changes="[rename] $(echo $line | awk '{print $2 $3 $4}')" ;;
      "modified" ) added_changes="[improve] $(echo $line | awk '{print $2}')" ;;
    esac
    commit_message="$commit_message $added_changes"
  done
  echo $commit_message
}

git_commit_automatically() {
  if [ $# != 0 ]; then
    for i in $*; do
      str="$str${str:++}$i"
    done
  fi
  commit_message=$( git status \
    | sed '1,/Changes to be committed/ d' \
    | sed '1,/^$/ d' \
    | sed '/^$/,$ d' \
    | loop
  )
  git commit -m "$commit_message $str"
}


git_commit_automatically
