#!/bin/zsh

battery=$(/usr/bin/pmset -g ps | awk '{ if (NR == 2) print $2 " " $3 }' | sed -e "s/;//g" -e "s/%//")
battery_quantity=$(echo $battery | awk '{print $1}')
if [[ ! $battery =~ "discharging" ]]; then
  echo "#[bg=cyan]#[fg=black] ⚡ $battery_quantity% #[default]"
elif [ $battery_quantity -le 15 ]; then
  echo "#[bg=red]#[fg=white] $battery_quantity% #[default]"
else
  echo "#[bg=cyan]#[fg=black] $battery_quantity% #[default]"
fi
