#!/bin/sh

ssid=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I \
  | grep " SSID" \
  | awk '{$1="";print}' \
  | sed "s/ //"`

if [ -n "$ssid" ]; then
  echo "#[bg=blue]#[fg=white] $ssid #[default]"
else
  echo "#[bg=blue]#[fg=white] ✘ #[default]"
fi
