brew 'git'
brew 'lua'
brew 'mongodb'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ruby'
brew 'tmux'
brew 'vim', args: ['with-lua']
brew 'zsh'
brew 'coreutils'
brew 'homebrew/dupes/libiconv'

tap 'caskroom/cask'
brew 'brew-cask'

cask 'iterm2'
cask 'google-chrome'
