[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'


[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Shougo/deol.nvim'

#[[plugins]]
#repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'icymind/NeoSolarized'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'lervag/vimtex'
