[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'


[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'icymind/NeoSolarized'

[[plugins]]
repo = 'Yggdroot/indentLine'
